### ISSUE TITLE
Mod prevents sorting on work tab

### ISSUE THREAD

**Issue by Asharas** [krypt-lynx/PawnTableGrouped#5]
Hi!

As the title says the mod prevents sorting pawns by skill level on the work tab. 

Tested with vanilla (core + all DLC).  

It'd be nice to have both sorting and grouping :)

**Comment by Asharas** [comment]
I realised I could disable the mod for that specific tab so I can enjoy the mod on others.  

Still if you could fix that it could be usefull to sort by skill and, for example, slave status

**Comment by krypt-lynx** [comment]
It looks like table is not getting updated. You can click on header, close tab and open in again. Still an issue to fix, though

**Comment by krypt-lynx** [comment]
Fixed in 2.0.2.
This repo is not yet updated, though
